package com.rfchina.community.persistence.mapper;

import com.rfchina.community.persistence.model.OpenOrder;
import com.rfchina.community.persistence.model.OpenOrderExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface OpenOrderMapper extends BaseMapper<OpenOrder,OpenOrderExample,Long> {
    @SelectProvider(type=OpenOrderSqlProvider.class, method="countByExample")
    long countByExample(OpenOrderExample example);

    @DeleteProvider(type=OpenOrderSqlProvider.class, method="deleteByExample")
    int deleteByExample(OpenOrderExample example);

    @Delete({
        "delete from open_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into open_order (total_id, account_id, ",
        "think_account_id, community_id, ",
        "app_id, service_id, ",
        "uid, caution_id, pay_channel, ",
        "out_trade_no, client_ip, ",
        "project_type, trade_type, ",
        "weixin_open_id, expire_time, ",
        "bussiness_type, create_time, ",
        "update_time, bill_status, ",
        "bill_id, bill_create_time, ",
        "community_trade_no, bill_finished_time, ",
        "total_amount, platform_charge, ",
        "platform_charge_rate, service_charge, ",
        "service_charge_rate, receipt_amount, ",
        "think_charge_rate, think_charge, ",
        "tixian_thrid, tixian_community, ",
        "refund_status, refund_reason, ",
        "refund_id, refund_remark, ",
        "refund_create_time, refund_money, ",
        "refund_bill_id, refund_sub_bill_id, ",
        "refund_account_id, same_way, ",
        "withdraw_status, type, ",
        "service_charge_status, balance_status, ",
        "service_charge_bill_id, service_account, ",
        "service_account_mchid, merchant_bill_id, ",
        "think_bill_id, bill_split_status, ",
        "bill_split_time, split_amount, ",
        "open_id, out_status, ",
        "out_status_content, settle_id, ",
        "pf_balance_status, pf_bussiness_balance_status, ",
        "pf_refund_status, pf_refund_time, ",
        "subject, body, detail, ",
        "task_id, emp_guid, ",
        "emp_phone, emp_name, ",
        "task_rel_id, goods_detail)",
        "values (#{totalId,jdbcType=BIGINT}, #{accountId,jdbcType=VARCHAR}, ",
        "#{thinkAccountId,jdbcType=VARCHAR}, #{communityId,jdbcType=BIGINT}, ",
        "#{appId,jdbcType=BIGINT}, #{serviceId,jdbcType=INTEGER}, ",
        "#{uid,jdbcType=BIGINT}, #{cautionId,jdbcType=BIGINT}, #{payChannel,jdbcType=VARCHAR}, ",
        "#{outTradeNo,jdbcType=VARCHAR}, #{clientIp,jdbcType=VARCHAR}, ",
        "#{projectType,jdbcType=VARCHAR}, #{tradeType,jdbcType=VARCHAR}, ",
        "#{weixinOpenId,jdbcType=VARCHAR}, #{expireTime,jdbcType=TIMESTAMP}, ",
        "#{bussinessType,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{billStatus,jdbcType=INTEGER}, ",
        "#{billId,jdbcType=VARCHAR}, #{billCreateTime,jdbcType=TIMESTAMP}, ",
        "#{communityTradeNo,jdbcType=VARCHAR}, #{billFinishedTime,jdbcType=TIMESTAMP}, ",
        "#{totalAmount,jdbcType=DECIMAL}, #{platformCharge,jdbcType=DECIMAL}, ",
        "#{platformChargeRate,jdbcType=DECIMAL}, #{serviceCharge,jdbcType=DECIMAL}, ",
        "#{serviceChargeRate,jdbcType=DECIMAL}, #{receiptAmount,jdbcType=DECIMAL}, ",
        "#{thinkChargeRate,jdbcType=DECIMAL}, #{thinkCharge,jdbcType=DECIMAL}, ",
        "#{tixianThrid,jdbcType=VARCHAR}, #{tixianCommunity,jdbcType=VARCHAR}, ",
        "#{refundStatus,jdbcType=INTEGER}, #{refundReason,jdbcType=VARCHAR}, ",
        "#{refundId,jdbcType=VARCHAR}, #{refundRemark,jdbcType=VARCHAR}, ",
        "#{refundCreateTime,jdbcType=TIMESTAMP}, #{refundMoney,jdbcType=DECIMAL}, ",
        "#{refundBillId,jdbcType=VARCHAR}, #{refundSubBillId,jdbcType=VARCHAR}, ",
        "#{refundAccountId,jdbcType=VARCHAR}, #{sameWay,jdbcType=INTEGER}, ",
        "#{withdrawStatus,jdbcType=INTEGER}, #{type,jdbcType=INTEGER}, ",
        "#{serviceChargeStatus,jdbcType=INTEGER}, #{balanceStatus,jdbcType=INTEGER}, ",
        "#{serviceChargeBillId,jdbcType=VARCHAR}, #{serviceAccount,jdbcType=VARCHAR}, ",
        "#{serviceAccountMchid,jdbcType=VARCHAR}, #{merchantBillId,jdbcType=VARCHAR}, ",
        "#{thinkBillId,jdbcType=VARCHAR}, #{billSplitStatus,jdbcType=INTEGER}, ",
        "#{billSplitTime,jdbcType=TIMESTAMP}, #{splitAmount,jdbcType=DECIMAL}, ",
        "#{openId,jdbcType=VARCHAR}, #{outStatus,jdbcType=INTEGER}, ",
        "#{outStatusContent,jdbcType=VARCHAR}, #{settleId,jdbcType=VARCHAR}, ",
        "#{pfBalanceStatus,jdbcType=INTEGER}, #{pfBussinessBalanceStatus,jdbcType=INTEGER}, ",
        "#{pfRefundStatus,jdbcType=INTEGER}, #{pfRefundTime,jdbcType=TIMESTAMP}, ",
        "#{subject,jdbcType=VARCHAR}, #{body,jdbcType=VARCHAR}, #{detail,jdbcType=VARCHAR}, ",
        "#{taskId,jdbcType=BIGINT}, #{empGuid,jdbcType=VARCHAR}, ",
        "#{empPhone,jdbcType=VARCHAR}, #{empName,jdbcType=VARCHAR}, ",
        "#{taskRelId,jdbcType=BIGINT}, #{goodsDetail,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(OpenOrder record);

    @InsertProvider(type=OpenOrderSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(OpenOrder record);

    @SelectProvider(type=OpenOrderSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="total_id", property="totalId", jdbcType=JdbcType.BIGINT),
        @Result(column="account_id", property="accountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="think_account_id", property="thinkAccountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="community_id", property="communityId", jdbcType=JdbcType.BIGINT),
        @Result(column="app_id", property="appId", jdbcType=JdbcType.BIGINT),
        @Result(column="service_id", property="serviceId", jdbcType=JdbcType.INTEGER),
        @Result(column="uid", property="uid", jdbcType=JdbcType.BIGINT),
        @Result(column="caution_id", property="cautionId", jdbcType=JdbcType.BIGINT),
        @Result(column="pay_channel", property="payChannel", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_trade_no", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_ip", property="clientIp", jdbcType=JdbcType.VARCHAR),
        @Result(column="project_type", property="projectType", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_type", property="tradeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="weixin_open_id", property="weixinOpenId", jdbcType=JdbcType.VARCHAR),
        @Result(column="expire_time", property="expireTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bussiness_type", property="bussinessType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bill_status", property="billStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="bill_id", property="billId", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_create_time", property="billCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="community_trade_no", property="communityTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_finished_time", property="billFinishedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="total_amount", property="totalAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="platform_charge", property="platformCharge", jdbcType=JdbcType.DECIMAL),
        @Result(column="platform_charge_rate", property="platformChargeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="service_charge", property="serviceCharge", jdbcType=JdbcType.DECIMAL),
        @Result(column="service_charge_rate", property="serviceChargeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="receipt_amount", property="receiptAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="think_charge_rate", property="thinkChargeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="think_charge", property="thinkCharge", jdbcType=JdbcType.DECIMAL),
        @Result(column="tixian_thrid", property="tixianThrid", jdbcType=JdbcType.VARCHAR),
        @Result(column="tixian_community", property="tixianCommunity", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_status", property="refundStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="refund_reason", property="refundReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_id", property="refundId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_remark", property="refundRemark", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_create_time", property="refundCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="refund_money", property="refundMoney", jdbcType=JdbcType.DECIMAL),
        @Result(column="refund_bill_id", property="refundBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_sub_bill_id", property="refundSubBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_account_id", property="refundAccountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="same_way", property="sameWay", jdbcType=JdbcType.INTEGER),
        @Result(column="withdraw_status", property="withdrawStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="service_charge_status", property="serviceChargeStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="balance_status", property="balanceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="service_charge_bill_id", property="serviceChargeBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="service_account", property="serviceAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="service_account_mchid", property="serviceAccountMchid", jdbcType=JdbcType.VARCHAR),
        @Result(column="merchant_bill_id", property="merchantBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="think_bill_id", property="thinkBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_split_status", property="billSplitStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="bill_split_time", property="billSplitTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="split_amount", property="splitAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_status", property="outStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="out_status_content", property="outStatusContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="settle_id", property="settleId", jdbcType=JdbcType.VARCHAR),
        @Result(column="pf_balance_status", property="pfBalanceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="pf_bussiness_balance_status", property="pfBussinessBalanceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="pf_refund_status", property="pfRefundStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="pf_refund_time", property="pfRefundTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="subject", property="subject", jdbcType=JdbcType.VARCHAR),
        @Result(column="body", property="body", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail", property="detail", jdbcType=JdbcType.VARCHAR),
        @Result(column="task_id", property="taskId", jdbcType=JdbcType.BIGINT),
        @Result(column="emp_guid", property="empGuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="emp_phone", property="empPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="emp_name", property="empName", jdbcType=JdbcType.VARCHAR),
        @Result(column="task_rel_id", property="taskRelId", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_detail", property="goodsDetail", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<OpenOrder> selectByExampleWithBLOBs(OpenOrderExample example);

    @SelectProvider(type=OpenOrderSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="total_id", property="totalId", jdbcType=JdbcType.BIGINT),
        @Result(column="account_id", property="accountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="think_account_id", property="thinkAccountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="community_id", property="communityId", jdbcType=JdbcType.BIGINT),
        @Result(column="app_id", property="appId", jdbcType=JdbcType.BIGINT),
        @Result(column="service_id", property="serviceId", jdbcType=JdbcType.INTEGER),
        @Result(column="uid", property="uid", jdbcType=JdbcType.BIGINT),
        @Result(column="caution_id", property="cautionId", jdbcType=JdbcType.BIGINT),
        @Result(column="pay_channel", property="payChannel", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_trade_no", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_ip", property="clientIp", jdbcType=JdbcType.VARCHAR),
        @Result(column="project_type", property="projectType", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_type", property="tradeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="weixin_open_id", property="weixinOpenId", jdbcType=JdbcType.VARCHAR),
        @Result(column="expire_time", property="expireTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bussiness_type", property="bussinessType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bill_status", property="billStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="bill_id", property="billId", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_create_time", property="billCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="community_trade_no", property="communityTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_finished_time", property="billFinishedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="total_amount", property="totalAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="platform_charge", property="platformCharge", jdbcType=JdbcType.DECIMAL),
        @Result(column="platform_charge_rate", property="platformChargeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="service_charge", property="serviceCharge", jdbcType=JdbcType.DECIMAL),
        @Result(column="service_charge_rate", property="serviceChargeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="receipt_amount", property="receiptAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="think_charge_rate", property="thinkChargeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="think_charge", property="thinkCharge", jdbcType=JdbcType.DECIMAL),
        @Result(column="tixian_thrid", property="tixianThrid", jdbcType=JdbcType.VARCHAR),
        @Result(column="tixian_community", property="tixianCommunity", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_status", property="refundStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="refund_reason", property="refundReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_id", property="refundId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_remark", property="refundRemark", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_create_time", property="refundCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="refund_money", property="refundMoney", jdbcType=JdbcType.DECIMAL),
        @Result(column="refund_bill_id", property="refundBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_sub_bill_id", property="refundSubBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_account_id", property="refundAccountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="same_way", property="sameWay", jdbcType=JdbcType.INTEGER),
        @Result(column="withdraw_status", property="withdrawStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="service_charge_status", property="serviceChargeStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="balance_status", property="balanceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="service_charge_bill_id", property="serviceChargeBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="service_account", property="serviceAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="service_account_mchid", property="serviceAccountMchid", jdbcType=JdbcType.VARCHAR),
        @Result(column="merchant_bill_id", property="merchantBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="think_bill_id", property="thinkBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_split_status", property="billSplitStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="bill_split_time", property="billSplitTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="split_amount", property="splitAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_status", property="outStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="out_status_content", property="outStatusContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="settle_id", property="settleId", jdbcType=JdbcType.VARCHAR),
        @Result(column="pf_balance_status", property="pfBalanceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="pf_bussiness_balance_status", property="pfBussinessBalanceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="pf_refund_status", property="pfRefundStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="pf_refund_time", property="pfRefundTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="subject", property="subject", jdbcType=JdbcType.VARCHAR),
        @Result(column="body", property="body", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail", property="detail", jdbcType=JdbcType.VARCHAR),
        @Result(column="task_id", property="taskId", jdbcType=JdbcType.BIGINT),
        @Result(column="emp_guid", property="empGuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="emp_phone", property="empPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="emp_name", property="empName", jdbcType=JdbcType.VARCHAR),
        @Result(column="task_rel_id", property="taskRelId", jdbcType=JdbcType.BIGINT)
    })
    List<OpenOrder> selectByExample(OpenOrderExample example);

    @Select({
        "select",
        "id, total_id, account_id, think_account_id, community_id, app_id, service_id, ",
        "uid, caution_id, pay_channel, out_trade_no, client_ip, project_type, trade_type, ",
        "weixin_open_id, expire_time, bussiness_type, create_time, update_time, bill_status, ",
        "bill_id, bill_create_time, community_trade_no, bill_finished_time, total_amount, ",
        "platform_charge, platform_charge_rate, service_charge, service_charge_rate, ",
        "receipt_amount, think_charge_rate, think_charge, tixian_thrid, tixian_community, ",
        "refund_status, refund_reason, refund_id, refund_remark, refund_create_time, ",
        "refund_money, refund_bill_id, refund_sub_bill_id, refund_account_id, same_way, ",
        "withdraw_status, type, service_charge_status, balance_status, service_charge_bill_id, ",
        "service_account, service_account_mchid, merchant_bill_id, think_bill_id, bill_split_status, ",
        "bill_split_time, split_amount, open_id, out_status, out_status_content, settle_id, ",
        "pf_balance_status, pf_bussiness_balance_status, pf_refund_status, pf_refund_time, ",
        "subject, body, detail, task_id, emp_guid, emp_phone, emp_name, task_rel_id, ",
        "goods_detail",
        "from open_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="total_id", property="totalId", jdbcType=JdbcType.BIGINT),
        @Result(column="account_id", property="accountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="think_account_id", property="thinkAccountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="community_id", property="communityId", jdbcType=JdbcType.BIGINT),
        @Result(column="app_id", property="appId", jdbcType=JdbcType.BIGINT),
        @Result(column="service_id", property="serviceId", jdbcType=JdbcType.INTEGER),
        @Result(column="uid", property="uid", jdbcType=JdbcType.BIGINT),
        @Result(column="caution_id", property="cautionId", jdbcType=JdbcType.BIGINT),
        @Result(column="pay_channel", property="payChannel", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_trade_no", property="outTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_ip", property="clientIp", jdbcType=JdbcType.VARCHAR),
        @Result(column="project_type", property="projectType", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_type", property="tradeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="weixin_open_id", property="weixinOpenId", jdbcType=JdbcType.VARCHAR),
        @Result(column="expire_time", property="expireTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bussiness_type", property="bussinessType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bill_status", property="billStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="bill_id", property="billId", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_create_time", property="billCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="community_trade_no", property="communityTradeNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_finished_time", property="billFinishedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="total_amount", property="totalAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="platform_charge", property="platformCharge", jdbcType=JdbcType.DECIMAL),
        @Result(column="platform_charge_rate", property="platformChargeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="service_charge", property="serviceCharge", jdbcType=JdbcType.DECIMAL),
        @Result(column="service_charge_rate", property="serviceChargeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="receipt_amount", property="receiptAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="think_charge_rate", property="thinkChargeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="think_charge", property="thinkCharge", jdbcType=JdbcType.DECIMAL),
        @Result(column="tixian_thrid", property="tixianThrid", jdbcType=JdbcType.VARCHAR),
        @Result(column="tixian_community", property="tixianCommunity", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_status", property="refundStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="refund_reason", property="refundReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_id", property="refundId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_remark", property="refundRemark", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_create_time", property="refundCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="refund_money", property="refundMoney", jdbcType=JdbcType.DECIMAL),
        @Result(column="refund_bill_id", property="refundBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_sub_bill_id", property="refundSubBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="refund_account_id", property="refundAccountId", jdbcType=JdbcType.VARCHAR),
        @Result(column="same_way", property="sameWay", jdbcType=JdbcType.INTEGER),
        @Result(column="withdraw_status", property="withdrawStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="service_charge_status", property="serviceChargeStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="balance_status", property="balanceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="service_charge_bill_id", property="serviceChargeBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="service_account", property="serviceAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="service_account_mchid", property="serviceAccountMchid", jdbcType=JdbcType.VARCHAR),
        @Result(column="merchant_bill_id", property="merchantBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="think_bill_id", property="thinkBillId", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_split_status", property="billSplitStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="bill_split_time", property="billSplitTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="split_amount", property="splitAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_status", property="outStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="out_status_content", property="outStatusContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="settle_id", property="settleId", jdbcType=JdbcType.VARCHAR),
        @Result(column="pf_balance_status", property="pfBalanceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="pf_bussiness_balance_status", property="pfBussinessBalanceStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="pf_refund_status", property="pfRefundStatus", jdbcType=JdbcType.INTEGER),
        @Result(column="pf_refund_time", property="pfRefundTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="subject", property="subject", jdbcType=JdbcType.VARCHAR),
        @Result(column="body", property="body", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail", property="detail", jdbcType=JdbcType.VARCHAR),
        @Result(column="task_id", property="taskId", jdbcType=JdbcType.BIGINT),
        @Result(column="emp_guid", property="empGuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="emp_phone", property="empPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="emp_name", property="empName", jdbcType=JdbcType.VARCHAR),
        @Result(column="task_rel_id", property="taskRelId", jdbcType=JdbcType.BIGINT),
        @Result(column="goods_detail", property="goodsDetail", jdbcType=JdbcType.LONGVARCHAR)
    })
    OpenOrder selectByPrimaryKey(Long id);

    @UpdateProvider(type=OpenOrderSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OpenOrder record, @Param("example") OpenOrderExample example);

    @UpdateProvider(type=OpenOrderSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") OpenOrder record, @Param("example") OpenOrderExample example);

    @UpdateProvider(type=OpenOrderSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OpenOrder record, @Param("example") OpenOrderExample example);

    @UpdateProvider(type=OpenOrderSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OpenOrder record);

    @Update({
        "update open_order",
        "set total_id = #{totalId,jdbcType=BIGINT},",
          "account_id = #{accountId,jdbcType=VARCHAR},",
          "think_account_id = #{thinkAccountId,jdbcType=VARCHAR},",
          "community_id = #{communityId,jdbcType=BIGINT},",
          "app_id = #{appId,jdbcType=BIGINT},",
          "service_id = #{serviceId,jdbcType=INTEGER},",
          "uid = #{uid,jdbcType=BIGINT},",
          "caution_id = #{cautionId,jdbcType=BIGINT},",
          "pay_channel = #{payChannel,jdbcType=VARCHAR},",
          "out_trade_no = #{outTradeNo,jdbcType=VARCHAR},",
          "client_ip = #{clientIp,jdbcType=VARCHAR},",
          "project_type = #{projectType,jdbcType=VARCHAR},",
          "trade_type = #{tradeType,jdbcType=VARCHAR},",
          "weixin_open_id = #{weixinOpenId,jdbcType=VARCHAR},",
          "expire_time = #{expireTime,jdbcType=TIMESTAMP},",
          "bussiness_type = #{bussinessType,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "bill_status = #{billStatus,jdbcType=INTEGER},",
          "bill_id = #{billId,jdbcType=VARCHAR},",
          "bill_create_time = #{billCreateTime,jdbcType=TIMESTAMP},",
          "community_trade_no = #{communityTradeNo,jdbcType=VARCHAR},",
          "bill_finished_time = #{billFinishedTime,jdbcType=TIMESTAMP},",
          "total_amount = #{totalAmount,jdbcType=DECIMAL},",
          "platform_charge = #{platformCharge,jdbcType=DECIMAL},",
          "platform_charge_rate = #{platformChargeRate,jdbcType=DECIMAL},",
          "service_charge = #{serviceCharge,jdbcType=DECIMAL},",
          "service_charge_rate = #{serviceChargeRate,jdbcType=DECIMAL},",
          "receipt_amount = #{receiptAmount,jdbcType=DECIMAL},",
          "think_charge_rate = #{thinkChargeRate,jdbcType=DECIMAL},",
          "think_charge = #{thinkCharge,jdbcType=DECIMAL},",
          "tixian_thrid = #{tixianThrid,jdbcType=VARCHAR},",
          "tixian_community = #{tixianCommunity,jdbcType=VARCHAR},",
          "refund_status = #{refundStatus,jdbcType=INTEGER},",
          "refund_reason = #{refundReason,jdbcType=VARCHAR},",
          "refund_id = #{refundId,jdbcType=VARCHAR},",
          "refund_remark = #{refundRemark,jdbcType=VARCHAR},",
          "refund_create_time = #{refundCreateTime,jdbcType=TIMESTAMP},",
          "refund_money = #{refundMoney,jdbcType=DECIMAL},",
          "refund_bill_id = #{refundBillId,jdbcType=VARCHAR},",
          "refund_sub_bill_id = #{refundSubBillId,jdbcType=VARCHAR},",
          "refund_account_id = #{refundAccountId,jdbcType=VARCHAR},",
          "same_way = #{sameWay,jdbcType=INTEGER},",
          "withdraw_status = #{withdrawStatus,jdbcType=INTEGER},",
          "type = #{type,jdbcType=INTEGER},",
          "service_charge_status = #{serviceChargeStatus,jdbcType=INTEGER},",
          "balance_status = #{balanceStatus,jdbcType=INTEGER},",
          "service_charge_bill_id = #{serviceChargeBillId,jdbcType=VARCHAR},",
          "service_account = #{serviceAccount,jdbcType=VARCHAR},",
          "service_account_mchid = #{serviceAccountMchid,jdbcType=VARCHAR},",
          "merchant_bill_id = #{merchantBillId,jdbcType=VARCHAR},",
          "think_bill_id = #{thinkBillId,jdbcType=VARCHAR},",
          "bill_split_status = #{billSplitStatus,jdbcType=INTEGER},",
          "bill_split_time = #{billSplitTime,jdbcType=TIMESTAMP},",
          "split_amount = #{splitAmount,jdbcType=DECIMAL},",
          "open_id = #{openId,jdbcType=VARCHAR},",
          "out_status = #{outStatus,jdbcType=INTEGER},",
          "out_status_content = #{outStatusContent,jdbcType=VARCHAR},",
          "settle_id = #{settleId,jdbcType=VARCHAR},",
          "pf_balance_status = #{pfBalanceStatus,jdbcType=INTEGER},",
          "pf_bussiness_balance_status = #{pfBussinessBalanceStatus,jdbcType=INTEGER},",
          "pf_refund_status = #{pfRefundStatus,jdbcType=INTEGER},",
          "pf_refund_time = #{pfRefundTime,jdbcType=TIMESTAMP},",
          "subject = #{subject,jdbcType=VARCHAR},",
          "body = #{body,jdbcType=VARCHAR},",
          "detail = #{detail,jdbcType=VARCHAR},",
          "task_id = #{taskId,jdbcType=BIGINT},",
          "emp_guid = #{empGuid,jdbcType=VARCHAR},",
          "emp_phone = #{empPhone,jdbcType=VARCHAR},",
          "emp_name = #{empName,jdbcType=VARCHAR},",
          "task_rel_id = #{taskRelId,jdbcType=BIGINT},",
          "goods_detail = #{goodsDetail,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(OpenOrder record);

    @Update({
        "update open_order",
        "set total_id = #{totalId,jdbcType=BIGINT},",
          "account_id = #{accountId,jdbcType=VARCHAR},",
          "think_account_id = #{thinkAccountId,jdbcType=VARCHAR},",
          "community_id = #{communityId,jdbcType=BIGINT},",
          "app_id = #{appId,jdbcType=BIGINT},",
          "service_id = #{serviceId,jdbcType=INTEGER},",
          "uid = #{uid,jdbcType=BIGINT},",
          "caution_id = #{cautionId,jdbcType=BIGINT},",
          "pay_channel = #{payChannel,jdbcType=VARCHAR},",
          "out_trade_no = #{outTradeNo,jdbcType=VARCHAR},",
          "client_ip = #{clientIp,jdbcType=VARCHAR},",
          "project_type = #{projectType,jdbcType=VARCHAR},",
          "trade_type = #{tradeType,jdbcType=VARCHAR},",
          "weixin_open_id = #{weixinOpenId,jdbcType=VARCHAR},",
          "expire_time = #{expireTime,jdbcType=TIMESTAMP},",
          "bussiness_type = #{bussinessType,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "bill_status = #{billStatus,jdbcType=INTEGER},",
          "bill_id = #{billId,jdbcType=VARCHAR},",
          "bill_create_time = #{billCreateTime,jdbcType=TIMESTAMP},",
          "community_trade_no = #{communityTradeNo,jdbcType=VARCHAR},",
          "bill_finished_time = #{billFinishedTime,jdbcType=TIMESTAMP},",
          "total_amount = #{totalAmount,jdbcType=DECIMAL},",
          "platform_charge = #{platformCharge,jdbcType=DECIMAL},",
          "platform_charge_rate = #{platformChargeRate,jdbcType=DECIMAL},",
          "service_charge = #{serviceCharge,jdbcType=DECIMAL},",
          "service_charge_rate = #{serviceChargeRate,jdbcType=DECIMAL},",
          "receipt_amount = #{receiptAmount,jdbcType=DECIMAL},",
          "think_charge_rate = #{thinkChargeRate,jdbcType=DECIMAL},",
          "think_charge = #{thinkCharge,jdbcType=DECIMAL},",
          "tixian_thrid = #{tixianThrid,jdbcType=VARCHAR},",
          "tixian_community = #{tixianCommunity,jdbcType=VARCHAR},",
          "refund_status = #{refundStatus,jdbcType=INTEGER},",
          "refund_reason = #{refundReason,jdbcType=VARCHAR},",
          "refund_id = #{refundId,jdbcType=VARCHAR},",
          "refund_remark = #{refundRemark,jdbcType=VARCHAR},",
          "refund_create_time = #{refundCreateTime,jdbcType=TIMESTAMP},",
          "refund_money = #{refundMoney,jdbcType=DECIMAL},",
          "refund_bill_id = #{refundBillId,jdbcType=VARCHAR},",
          "refund_sub_bill_id = #{refundSubBillId,jdbcType=VARCHAR},",
          "refund_account_id = #{refundAccountId,jdbcType=VARCHAR},",
          "same_way = #{sameWay,jdbcType=INTEGER},",
          "withdraw_status = #{withdrawStatus,jdbcType=INTEGER},",
          "type = #{type,jdbcType=INTEGER},",
          "service_charge_status = #{serviceChargeStatus,jdbcType=INTEGER},",
          "balance_status = #{balanceStatus,jdbcType=INTEGER},",
          "service_charge_bill_id = #{serviceChargeBillId,jdbcType=VARCHAR},",
          "service_account = #{serviceAccount,jdbcType=VARCHAR},",
          "service_account_mchid = #{serviceAccountMchid,jdbcType=VARCHAR},",
          "merchant_bill_id = #{merchantBillId,jdbcType=VARCHAR},",
          "think_bill_id = #{thinkBillId,jdbcType=VARCHAR},",
          "bill_split_status = #{billSplitStatus,jdbcType=INTEGER},",
          "bill_split_time = #{billSplitTime,jdbcType=TIMESTAMP},",
          "split_amount = #{splitAmount,jdbcType=DECIMAL},",
          "open_id = #{openId,jdbcType=VARCHAR},",
          "out_status = #{outStatus,jdbcType=INTEGER},",
          "out_status_content = #{outStatusContent,jdbcType=VARCHAR},",
          "settle_id = #{settleId,jdbcType=VARCHAR},",
          "pf_balance_status = #{pfBalanceStatus,jdbcType=INTEGER},",
          "pf_bussiness_balance_status = #{pfBussinessBalanceStatus,jdbcType=INTEGER},",
          "pf_refund_status = #{pfRefundStatus,jdbcType=INTEGER},",
          "pf_refund_time = #{pfRefundTime,jdbcType=TIMESTAMP},",
          "subject = #{subject,jdbcType=VARCHAR},",
          "body = #{body,jdbcType=VARCHAR},",
          "detail = #{detail,jdbcType=VARCHAR},",
          "task_id = #{taskId,jdbcType=BIGINT},",
          "emp_guid = #{empGuid,jdbcType=VARCHAR},",
          "emp_phone = #{empPhone,jdbcType=VARCHAR},",
          "emp_name = #{empName,jdbcType=VARCHAR},",
          "task_rel_id = #{taskRelId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OpenOrder record);
}